spring.threads.virtual.enabled=true
spring.main.keep-alive=true

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
benchmark.kafka.topic=${BENCHMARK_KAFKA_TOPIC:bids}
benchmark.delivery.mode=${BENCHMARK_DELIVERY_MODE:confirm}
benchmark.kafka.acks=${BENCHMARK_KAFKA_ACKS:1}
benchmark.kafka.linger.ms=${BENCHMARK_KAFKA_LINGER_MS:10}
benchmark.kafka.batch.bytes=${BENCHMARK_KAFKA_BATCH_BYTES:131072}
benchmark.kafka.request.timeout.ms=${BENCHMARK_KAFKA_REQUEST_TIMEOUT_MS:5000}
