services:
  go-receiver:
    build:
      context: ${GITHUB_WORKSPACE}/services/go-receiver
      dockerfile: Dockerfile
    environment:
      BENCHMARK_DELIVERY_MODE: http-only
    expose:
      - "8080"
